POST http://localhost:8080/events
content-type: application/json

{
  "name": "Fake name",
  "description": "Fake description.",
  "location": "Abuja, NG",
  "datetime": "2023-09-15T09:00:00Z",
  "user_id": 4
}