POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNDcxMzQyLCJ1c2VySWQiOjN9.1YRoeQlxtcRIAkEaaE9fiWvkcXx_Hxr5Qe7Ux4Hrvns

{
  "name": "Fake name 6",
  "description": "Fake description 5.",
  "location": "Accra, Ghana",
  "datetime": "2023-09-15T09:00:00Z"
}