POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNDc5OTU0LCJ1c2VySWQiOjR9.c17AJZvbrKJIwQLIsqvR6mOhqL5W8yArSVAzwzJmen0

{
  "name": "event 1",
  "description": "event 1 description.",
  "location": "Accra, Ghana",
  "datetime": "2023-09-15T09:00:00Z"
}